-- ==============================================================
-- HE Efficient and Industry Limited (E.F.T.) 完整生产数据库备份
-- 官方域名: www.efficientsh.com
-- 生成时间: 2026-09-22
-- ==============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 1. 产品表 (products)
DROP TABLE IF EXISTS ;
CREATE TABLE  (
  uid=0(root) gid=0(root) groups=0(root) int(11) NOT NULL AUTO_INCREMENT,
   int(11) NOT NULL DEFAULT 1,
   varchar(255) DEFAULT '工业设备',
   varchar(255) NOT NULL,
   varchar(500) DEFAULT '',
   varchar(100) DEFAULT '',
   varchar(100) DEFAULT '面议 / Negotiable',
   text,
   text,
   tinyint(1) DEFAULT 0,
   int(11) DEFAULT 100,
   decimal(10,2) DEFAULT 0.00,
  PRIMARY KEY (uid=0(root) gid=0(root) groups=0(root))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO  (uid=0(root) gid=0(root) groups=0(root), , , , , , , , , , , ) VALUES
(41, 4, '电子电气', 'CXH6-1D 单层船用环照灯 (红绿明光 3海里)', 'Single-Deck Marine All-Round Navigation Signal Light 3nm', 'CXH6-1D', '面议 / Negotiable', '/prophoto/cropped_1790079275695_4_CXH6-1D.jpg, /prophoto/ai_1790079262884_1_415.jpg', 'This all-round signal light provides 360° visibility at a distance of 3nm. It is built to IP55 protection standards and features a durable, corrosion-resistant steel body. The lamp assembly includes an ultraviolet-resistant polycarbonate cover and is rated for operation with 24V/110V/220V power systems. It meets international standards for maritime safety and navigation. The construction includes automated bottom leak holes for drainage and long-term durability on deck.', 0, 100, 0),
(40, 4, '电子电气', 'CXH4-1D 单层船用尾灯 (黄光 3海里)', 'Single-Deck Marine Stern Navigation Signal Light 3nm', 'CXH4-1D', '面议 / Negotiable', '/prophoto/cropped_1790079275269_3_CXH4-1D.jpg, /prophoto/ai_1790079262884_1_415.jpg', 'Designed for stern installation, this model offers a 3nm visibility distance across a 135° arc. It adheres to IP55 protection class standards and is crafted from high-quality steel with a corrosion-resistant coating. The unit includes a transparent/yellow polycarbonate lamp shade for effective light transmission and UV resistance. It is compliant with the GB/T 3028-1995 standard for marine electrical equipment. The compact design allows for easy maintenance and bulb replacement.', 0, 100, 0),
(39, 4, '电子电气', 'CXH3-1D 单层船用桅灯 (明光 6海里)', 'Single-Deck Marine Masthead Navigation Signal Light 6nm', 'CXH3-1D', '面议 / Negotiable', '/prophoto/cropped_1790079274830_2_CXH3-1D.jpg, /prophoto/ai_1790079262884_1_415.jpg', 'The CXH3-1D masthead light provides an enhanced 6nm visibility distance with a wide 225° horizontal arc. Built with a steel housing and protected to IP55 standards, it is highly resistant to corrosion and ultraviolet rays. It supports flexible electrical inputs of 24V 60W or 110V/220V 65W. The light is suitable for vessels of 50 meters or more, ensuring compliance with international maritime standards. It features an integrated B22d lamp holder and convenient bottom drainage holes.', 0, 100, 0),
(38, 4, '电子电气', 'CXH2-1D 单层船用左舷灯 (红光 3海里)', 'Single-Deck Marine Port Navigation Signal Light 3nm', 'CXH2-1D', '面议 / Negotiable', '/prophoto/cropped_1790079274477_1_CXH2-1D.jpg, /prophoto/ai_1790079262884_1_415.jpg', 'This port side navigation light offers a visibility distance of 3nm with a 112.5° light angle. It is constructed from robust steel with an IP55 protection rating and specialized mold-powder surface treatment. The unit supports 24V/110V/220V power inputs and utilizes an easily replaceable bulb system. It is fully compliant with the 1972 International Regulations for Preventing Collisions at Sea. The design incorporates automatic leak holes to ensure longevity in marine environments.', 0, 100, 0),
(37, 4, '电子电气', 'CXH1-1D 单层船用右舷灯 (绿光 3海里)', 'Single-Deck Marine Starboard Navigation Signal Light 3nm', 'CXH1-1D', '面议 / Negotiable', '/prophoto/cropped_1790079274068_0_CXH1-1D.jpg, /prophoto/ai_1790079262878_0_728.jpg', 'This signal light features a 3nm visibility distance with a 112.5° horizontal arc, designed for starboard side installation. It is housed in a durable steel casing with an IP55 protection class rating against dust and moisture. The light uses a 24V 60W or 110V/220V 65W bulb and is built with high-quality ultraviolet-resistant polycarbonate. It complies with international maritime collision prevention regulations and the GB/T 3028-1995 standard. The bottom of the light includes automatic leak holes for efficient water drainage.', 0, 100, 0),
(36, 4, '电子电气', 'CXH6-1D 单层船用环照灯 (红绿明 3海里)', 'Single-deck all-round navigation signal light with 3nm visibility', 'CXH6-1D', '面议 / Negotiable', '/prophoto/cropped_1790077498790_4_CXH6-1D.jpg, /prophoto/ai_1790077468792_1_49.jpg', 'This all-round navigation light provides a 360-degree horizontal lighting arc, essential for vessel signaling at night. It is constructed from heavy-duty steel with a corrosion-resistant coating and a durable polycarbonate lampshade. With a 3 nautical mile visibility rating and an IP55 protection grade, it is built for reliable performance in harsh conditions. The unit is designed to meet GB/T 3028-1995 standards for marine signal equipment.', 0, 100, 0),
(35, 4, '电子电气', 'CXH4-1D 单层船用尾灯 (明黄 3海里)', 'Single-deck stern navigation signal light with 3nm visibility', 'CXH4-1D', '面议 / Negotiable', '/prophoto/cropped_1790077498774_3_CXH4-1D.jpg, /prophoto/ai_1790077468792_1_49.jpg', 'Engineered for stern signaling, this light provides a 135-degree horizontal arc with a visibility of 3 nautical miles. It features a transparent yellow lens made of polycarbonate for long-term UV resistance. The steel body is powder-coated for exceptional corrosion resistance in marine applications. The unit is fully compliant with the 1972 international collision avoidance regulations and is rated IP55 for moisture and dust protection.', 0, 100, 0),
(34, 4, '电子电气', 'CXH3-1D 单层船用桅灯 (明光 6海里)', 'Single-deck masthead navigation signal light with 6nm visibility', 'CXH3-1D', '面议 / Negotiable', '/prophoto/cropped_1790077498759_2_CXH3-1D.jpg, /prophoto/ai_1790077468792_1_49.jpg', 'The CXH3-1D masthead light is intended for large vessels, providing superior signaling with a 6-nautical-mile visibility range. It utilizes a 225-degree horizontal arc for optimal navigation clarity. The lamp housing is made of quality steel with a specialized anti-corrosive coating, complemented by a transparent polycarbonate lens. It supports 24V/110V/220V power options with 60W/65W bulbs and adheres to IP55 protection standards.', 0, 100, 0),
(33, 4, '电子电气', 'CXH2-1D 单层船用左舷灯 (红光 3海里)', 'Single-deck port navigation signal light with 3nm visibility', 'CXH2-1D', '面议 / Negotiable', '/prophoto/cropped_1790077498746_1_CXH2-1D.jpg, /prophoto/ai_1790077468792_1_49.jpg', 'Designed for port-side identification on ships over 50 meters, this CXH2-1D unit delivers reliable red light signaling. It features a robust steel construction, anti-corrosive powder coating, and a durable UV-resistant polycarbonate lampshade. It offers a 112.5-degree horizontal lighting angle and a visibility distance of 3 nautical miles. The device is built to IP55 ingress protection standards and meets international collision prevention regulations.', 0, 100, 0),
(32, 4, '电子电气', 'CXH1-1D 单层船用右舷灯 (绿光 3海里)', 'Single-deck starboard navigation signal light with 3nm visibility', 'CXH1-1D', '面议 / Negotiable', '/prophoto/cropped_1790077498728_0_CXH1-1D.jpg, /prophoto/ai_1790077468791_0_430.jpg', 'This starboard signal light is designed for vessels 50 meters or longer. It features a high-quality steel housing with an anti-corrosive powder finish and a polycarbonate lens that is resistant to UV radiation. The light has a visibility range of 3 nautical miles and a horizontal arc of 112.5 degrees. It operates with a protection class of IP55, ensuring durability in harsh marine environments. The unit is compliant with the 1972 COLREGs and GB/T 3028-1995 standards.', 0, 100, 0),
(31, 7, '电子电气', 'CXH6-1D 单层船用环照灯 (红/绿/明光 3海里)', 'CXH6-1D Single-Deck Marine All-Round Navigation Light 3nm', 'CXH6-1D', '面议 / Negotiable', '/prophoto/ai_1790074204232_0_923.jpg, /prophoto/ai_1790074204233_1_230.jpg', 'The CXH6-1D is an all-round navigation light offering 360-degree visibility at a range of 3 nautical miles. It is available in red, green, or transparent color configurations to suit specific signaling needs. Built with a heavy-duty steel frame and high-quality polycarbonate optics, it provides excellent resistance to corrosion, shock, and ultraviolet rays. The unit holds an IP55 protection rating and complies with GB/T 3028-1995 and international maritime standards.', 0, 100, 0),
(30, 7, '电子电气', 'CXH4-1D 单层船用艉灯 (明/黄光 3海里)', 'CXH4-1D Single-Deck Marine Stern Navigation Light Transparent/Yellow 3nm', 'CXH4-1D', '面议 / Negotiable', '/prophoto/ai_1790074204232_0_923.jpg, /prophoto/ai_1790074204233_1_230.jpg', 'This CXH4-1D stern light features a 135-degree horizontal arc and is capable of displaying either transparent or yellow light. It provides a visibility distance of 3 nautical miles and is engineered for robust performance on ships 50m or larger. The assembly includes automatic leak holes to prevent water accumulation and is protected to IP55 standards. The device is constructed from durable steel and UV-resistant PC materials, meeting global maritime safety requirements.', 0, 100, 0),
(29, 7, '电子电气', 'CXH3-1D 单层船用桅灯 (明光 6海里)', 'CXH3-1D Single-Deck Marine Masthead Navigation Light Transparent 6nm', 'CXH3-1D', '面议 / Negotiable', '/prophoto/ai_1790074204232_0_923.jpg, /prophoto/ai_1790074204233_1_230.jpg', 'Designed for large vessels over 50m, this CXH3-1D masthead light emits a transparent/white light with a wide 225-degree horizontal arc. It offers a high visibility distance of 6 nautical miles and supports 24V/110V/220V power inputs. The housing is built from premium steel with a corrosion-resistant finish, paired with a resilient polycarbonate lampshade. The product conforms to international standards and features an IP55 ingress protection rating.', 0, 100, 0),
(28, 7, '电子电气', 'CXH2-1D 单层船用左舷灯 (红光 3海里)', 'CXH2-1D Single-Deck Marine Port Navigation Light Red 3nm', 'CXH2-1D', '面议 / Negotiable', '/prophoto/ai_1790074204232_0_923.jpg, /prophoto/ai_1790074204233_1_230.jpg', 'The CXH2-1D port navigation light provides a red light with a 112.5-degree horizontal arc, suitable for vessels 50m and above. It features a 3 nautical mile visibility range and an IP55 protection class. Constructed with a durable steel shell and polycarbonate lens, it ensures long-term resistance to ultraviolet radiation and environmental corrosion. This model complies with GB/T 3028-1995 and international maritime collision prevention regulations.', 0, 100, 0),
(27, 7, '电子电气', 'CXH1-1D 单层船用右舷灯 (绿光 3海里)', 'CXH1-1D Single-Deck Marine Starboard Navigation Light Green 3nm', 'CXH1-1D', '面议 / Negotiable', '/prophoto/ai_1790074204232_0_923.jpg', 'This CXH1-1D starboard navigation light is designed for ships 50m or above in length. It features a green light output with a horizontal arc of 112.5 degrees and a visibility distance of 3 nautical miles. The casing is made of high-quality steel with corrosion-resistant powder coating, and the lampshade is crafted from UV-resistant polycarbonate. It meets the 1972 International Regulations for Preventing Collisions at Sea and standard GB/T 3028-1995. The unit is rated IP55 for protection and weighs 4.9kg.', 0, 100, 0),
(26, 9, '机械五金', '工厂直销1寸-2寸平开家具门窗小合页静音铰链房门木盒礼品盒合页', '1-2 Inch Butt Hinges: Silent Furniture, Cabinet, Wooden Box, and Door Hardware Exporter', 'EFT-MD-1782', '面议 / Negotiable', '/prophoto/sourced_1790074086734_0_6c4ae222.jpg, /prophoto/sourced_1790074086803_1_23f18761.jpg, /prophoto/sourced_1790074086822_2_ea7d2862.jpg, /prophoto/sourced_1790074086842_3_8328ea24.jpg, /prophoto/sourced_1790074086865_4_75d63929.jpg, /prophoto/sourced_1790074086885_5_5bc9d48b.jpg', 'These high-precision butt hinges are engineered from premium-grade steel, ensuring exceptional structural integrity and long-term corrosion resistance for export markets. The design features an advanced silent-action mechanism, providing smooth, noise-free operation suitable for residential furniture, high-end wooden gift boxes, and interior cabinetry. Manufactured under strict ISO9001 quality management standards, each unit maintains tight dimensional tolerances to ensure a perfect flush-mount fit. The surface finish is electroplated to meet international CE and RoHS environmental compliance requirements, preventing oxidation during overseas shipping. These hinges offer superior load-bearing capacity and durability, making them an ideal hardware solution for both delicate handicraft applications and heavy-duty furniture assembly.', 1, 200, 68),
(25, 8, '医疗器械', '三功能医院医用电动全自动升降护理床五功能前倾后倾电动护理床', '3-Function & 5-Function Electric Hospital Nursing Bed with Automatic Height Adjustment and Trendelenburg Tilt', 'EFT-MD-0370', '面议 / Negotiable', '/prophoto/sourced_1790051031157_0_9ce1e926.jpg, /prophoto/sourced_1790051031224_1_49288df7.jpg, /prophoto/sourced_1790051031258_2_7110e28e.jpg, /prophoto/sourced_1790051031287_3_4b5e31b3.jpg, /prophoto/sourced_1790051031308_4_f630db00.jpg, /prophoto/sourced_1790051031326_5_21b61e88.jpg', 'This premium medical nursing bed features a reinforced cold-rolled steel frame with an electrostatic powder coating for superior corrosion resistance and long-term durability. It is equipped with medical-grade electric actuators offering smooth, quiet 3-function or 5-function adjustments, including height elevation, backrest, leg-rest, and Trendelenburg/Reverse Trendelenburg tilt capabilities. Designed for safety and efficiency in clinical environments, the bed features detachable ABS head and foot boards, tuck-away side rails, and high-load capacity central-locking casters. Every unit undergoes rigorous multi-stage quality control inspections to ensure full compliance with ISO9001, CE, and RoHS international medical equipment safety standards. Engineered for both ICU and general ward use, this model provides optimal ergonomic support for patients while ensuring high-precision control for nursing staff.', 1, 200, 68),
(24, 8, '医疗器械', '三功能医院医用电动全自动升降护理床五功能前倾后倾电动护理床', '3-Function & 5-Function Electric Hospital Nursing Bed with Automatic Height Adjustment and Trendelenburg Tilt', 'EFT-MD-0370', '面议 / Negotiable', '/prophoto/sourced_1790050029971_0_9ce1e926.jpg, /prophoto/sourced_1790050030207_1_49288df7.jpg, /prophoto/sourced_1790050030886_2_7110e28e.jpg, /prophoto/sourced_1790050031106_3_4b5e31b3.jpg, /prophoto/sourced_1790050031850_4_f630db00.jpg, /prophoto/sourced_1790050032052_5_21b61e88.jpg', 'Engineered for superior patient care and clinical versatility, this electric hospital nursing bed is constructed from high-strength cold-rolled steel with an anti-microbial powder-coated finish for optimal hygiene and durability. It features precision-controlled electric linear actuators that enable seamless adjustment of backrest elevation, leg support, overall height lifting, and advanced 5-function Trendelenburg/Reverse Trendelenburg tilting positions (+/- 12° to 15°). Equipped with high-grade PP tuck-away side rails, removable ABS head/footboards, and 125mm central-locking noiseless swivel casters, the bed ensures maximum patient safety and effortless maneuverability. Built to withstand continuous duty cycles with a safe working load (SWL) of up to 250 kg and precise movement tolerances, it ideal for ICU wards, long-term care facilities, and medical rehabilitation centers. Every unit undergoes rigorous load testing and electro-mechanical quality control in compliance with ISO13485, CE (MDR), and RoHS international export standards.', 1, 200, 68),
(23, 11, '橡塑制品', 'CHS长虹塑料A级耐寒束线尼龙扎带3*4*5*8*100*150*200*300批发', 'CHS Premium Grade Cold-Resistant Nylon Cable Ties, Various Sizes Available for Wholesale.', 'EFT-MD-5264', '面议 / Negotiable', '/prophoto/sourced_1790043198569_0_dd59bdbe.jpg, /prophoto/sourced_1790043198647_1_8e93cf9f.jpg, /prophoto/sourced_1790043198675_2_4c3287b6.jpg, /prophoto/sourced_1790043198696_3_4482f905.jpg, /prophoto/sourced_1790043198723_4_588dd3e1.jpg, /prophoto/sourced_1790043198744_5_19e41e30.jpg', 'Engineered from high-tenacity virgin nylon 66, these CHS-branded cable ties offer exceptional cold-weather resistance and tensile strength for demanding industrial environments. The design features a self-locking mechanism with rounded edges to ensure secure bundling while preventing wire insulation damage during installation. These products are manufactured under strict ISO9001 quality management systems, ensuring consistent dimensional tolerances and high-performance durability across all listed lengths and widths. They are fully compliant with CE and RoHS standards, making them suitable for reliable electrical, automotive, and infrastructure wiring management. Designed for long-term reliability, our ties maintain flexibility and impact resistance even in sub-zero export applications.', 1, 200, 68),
(22, 8, '医疗器械', '三功能医院医用电动全自动升降护理床五功能前倾后倾电动护理床', 'Professional 3 to 5-Function Electric Hospital Nursing Bed with Automatic Elevation and Tilt Control.', 'EFT-MD-0370', '面议 / Negotiable', '/prophoto/sourced_1790042475916_0_9ce1e926.jpg, /prophoto/sourced_1790042475998_1_49288df7.jpg, /prophoto/sourced_1790042476034_2_7110e28e.jpg, /prophoto/sourced_1790042476057_3_4b5e31b3.jpg, /prophoto/sourced_1790042476079_4_f630db00.jpg, /prophoto/sourced_1790042476100_5_21b61e88.jpg', 'This premium medical nursing bed features a reinforced cold-rolled steel frame with an electrostatic powder coating for superior corrosion resistance and long-term structural integrity. It offers versatile 3 to 5-function clinical positioning, including motorized backrest adjustment, knee elevation, and advanced Trendelenburg/Reverse Trendelenburg tilt capabilities. Engineered for heavy-duty hospital environments, the high-torque electric motor system ensures smooth, quiet, and precise patient height adjustments with a high static load capacity. Each unit is manufactured under strict ISO9001 quality management standards and complies with CE and RoHS safety certifications to meet global export requirements. Designed for patient comfort and caregiver efficiency, the bed includes high-impact modular side rails and a detachable head/foot board system for rapid maintenance and sanitation.', 1, 200, 68),
(21, 8, '医疗器械', '三功能医院医用电动全自动升降护理床五功能前倾后倾电动护理床', 'Professional 3 to 5-Function Electric Hospital Nursing Bed with Automatic Height Adjustment and Tilt', 'EFT-MD-0370', '面议 / Negotiable', '/prophoto/sourced_1790042092735_0_9ce1e926.jpg, /prophoto/sourced_1790042092816_1_49288df7.jpg, /prophoto/sourced_1790042092841_2_7110e28e.jpg, /prophoto/sourced_1790042092866_3_4b5e31b3.jpg, /prophoto/sourced_1790042092886_4_f630db00.jpg, /prophoto/sourced_1790042092908_5_21b61e88.jpg', 'This premium medical nursing bed features a reinforced cold-rolled steel frame with an electrostatic powder coating for superior corrosion resistance and durability. It offers advanced 3 to 5-function adjustability, including electronic backrest elevation, leg support, and Hi-Lo height adjustment with Trendelenburg and Reverse-Trendelenburg tilting capabilities. Engineered for high-acuity care, the unit incorporates medical-grade silent actuators for smooth, precise positioning and integrated ABS side rails with safety locking mechanisms. Every bed undergoes rigorous load-bearing and electrical safety testing to meet international ISO13485, CE, and RoHS compliance standards. Ideal for intensive care or long-term nursing, the design prioritizes patient ergonomics, infection control through removable headboards, and long-term mechanical reliability in demanding clinical environments.', 1, 200, 68),
(20, 11, '橡塑制品', 'CHS长虹塑料A级耐寒束线尼龙扎带3*4*5*8*100*150*200*300批发', 'CHS Premium Grade Cold-Resistant Nylon Cable Ties, Various Sizes Available for Wholesale Export', 'EFT-MD-5264', '面议 / Negotiable', '/prophoto/sourced_1789969739098_0_dd59bdbe.jpg, /prophoto/sourced_1789969739176_1_8e93cf9f.jpg, /prophoto/sourced_1789969739196_2_4c3287b6.jpg, /prophoto/sourced_1789969739217_3_4482f905.jpg, /prophoto/sourced_1789969739237_4_588dd3e1.jpg, /prophoto/sourced_1789969739259_5_19e41e30.jpg', 'These CHS-branded nylon cable ties are engineered from high-grade, cold-resistant polyamide 66, ensuring exceptional tensile strength and flexibility in sub-zero environments. The precision-molded locking mechanism features a robust pawl design that guarantees a secure, permanent grip across diverse industrial bundling applications. Our production process adheres to strict ISO9001 quality management standards, with every batch undergoing rigorous testing for heat resistance and mechanical fatigue. These cable ties are fully RoHS and CE compliant, free of hazardous substances, and suitable for demanding outdoor and indoor cable management projects. Available in multiple widths (3mm–8mm) and lengths (100mm–300mm), they offer consistent, high-performance durability for global export requirements.', 1, 200, 68),
(19, 9, '机械五金', '工厂直销1寸-2寸平开家具门窗小合页静音铰链房门木盒礼品盒合页', '1-2 Inch Silent Butt Hinges for Furniture, Cabinet Doors, Wood Boxes, and Gift Cases', 'EFT-MD-1782', '面议 / Negotiable', '/prophoto/sourced_1789969573509_0_6c4ae222.jpg, /prophoto/sourced_1789969573582_1_23f18761.jpg, /prophoto/sourced_1789969573606_2_ea7d2862.jpg, /prophoto/sourced_1789969573626_3_8328ea24.jpg, /prophoto/sourced_1789969573647_4_75d63929.jpg, /prophoto/sourced_1789969573668_5_5bc9d48b.jpg', 'These high-precision butt hinges are engineered from premium-grade steel, ensuring exceptional structural integrity and load-bearing capacity for diverse small-scale applications. The design features a silent-operation pivot mechanism that minimizes friction, providing smooth, consistent movement without squeaking. Each unit is precision-stamped to meet tight manufacturing tolerances, ensuring perfect alignment for cabinet doors, wooden jewelry boxes, and interior furniture pieces. Our production process adheres to rigorous ISO9001 quality management standards, with anti-corrosion surface treatments that comply with RoHS environmental regulations for export-grade reliability. These hinges undergo stringent quality inspection cycles to guarantee durability against mechanical wear and oxidation in varied environmental conditions.', 1, 200, 68),
(18, 8, '医疗器械', '医用护理床单双摇医疗床医院养老院中全曲便捷可开孔定制', 'Multi-Function Electric Medical Nursing Hospital Bed with Adjustable Elevation', 'EFT-MD-4542', '面议 / Negotiable', '/prophoto/sourced_1789969404279_0_ba24d39d.jpg, /prophoto/sourced_1789969404366_1_2bc912f6.jpg, /prophoto/sourced_1789969404393_2_ed527704.jpg, /prophoto/sourced_1789969404420_3_dc4aa55d.jpg, /prophoto/sourced_1789969404443_4_f45b2ade.jpg, /prophoto/sourced_1789969404466_5_781820ee.jpg', 'Manufactured from industrial-grade high-strength materials to meet stringent international standards. Engineered for superior structural reliability, corrosion resistance, and extended service life across heavy-duty operating environments. Every batch undergoes 100% factory dimensional and functional testing to ensure zero-defect shipment. Fully certified under ISO9001, CE, and RoHS international compliance guidelines for worldwide commercial export.', 1, 200, 68),
(17, 8, '医疗器械', '三功能医院医用电动全自动升降护理床五功能前倾后倾电动护理床', 'Multi-Function Electric Medical Nursing Hospital Bed with Adjustable Elevation', 'EFT-MD-0370', '面议 / Negotiable', '/prophoto/sourced_1789969307499_0_9ce1e926.jpg, /prophoto/sourced_1789969307576_1_49288df7.jpg, /prophoto/sourced_1789969307628_2_7110e28e.jpg, /prophoto/sourced_1789969307653_3_4b5e31b3.jpg, /prophoto/sourced_1789969307675_4_f630db00.jpg, /prophoto/sourced_1789969307696_5_21b61e88.jpg', 'Manufactured from industrial-grade high-strength materials to meet stringent international standards. Engineered for superior structural reliability, corrosion resistance, and extended service life across heavy-duty operating environments. Every batch undergoes 100% factory dimensional and functional testing to ensure zero-defect shipment. Fully certified under ISO9001, CE, and RoHS international compliance guidelines for worldwide commercial export.', 1, 200, 68),
(16, 8, '医疗器械', '三功能医用医院用电动全自动升降护理床五功能前后倾电动护理床', 'High Reliability Precision Engineered Export Unit', 'EFT-IND-6850', '面议 / Negotiable', '/prophoto/sourced_test.jpg', 'Standard: ISO9001 / CE / RoHS; Quality Inspection: 100% Factory Tested; Origin: Shanghai, China.', 0, 200, 88),
(15, 7, '电子电气', 'B111一拖二家用办公室无线遥控门铃', 'B111 1-to-2 Wireless Doorbell with Remote Control for Home and Office Use', 'EFT-B111-WIRELESS', '面议 / Negotiable', '/prophoto/sourced_1789893923162_0_1789893923657_309874659c.jpg, /prophoto/sourced_1789893923691_1_1789893923739_7fc1ca3e0c.jpg, /prophoto/sourced_1789893923765_2_1789893923781_1a99218e14.jpg, /prophoto/sourced_1789893923788_3_1789893923806_e81ceb7a30.jpg', 'Model: B111; Type: 1-to-2 (1 Receiver, 2 Transmitters); Power Source: AC Plug-in; Frequency: High-frequency wireless transmission; Application: Residential and Commercial; Certifications: CE/RoHS', 1, 500, 45),
(14, 7, '电子电气', 'F536无线家用门铃交流数码一拖一呼叫器按键可设不同铃声门铃', 'F536 Wireless AC Digital Doorbell with One-to-One Paging and Adjustable Ringtone Settings', 'EFT-F536', '面议 / Negotiable', '/prophoto/sourced_1789893885923_0_1789893886194_b6e1ac2f1c.jpg, /prophoto/sourced_1789893886227_1_1789893886277_518bc407b3.jpg, /prophoto/sourced_1789893886312_2_1789893886330_02c735a8e2.jpg, /prophoto/sourced_1789893886349_3_1789893886369_17ad44923d.jpg, /prophoto/sourced_1789893886373_4_1789893886390_5b18c12b23.jpg', 'Power Supply: AC; Connection Type: Wireless; Paging: One-to-One; Features: Adjustable Ringtones, Digital Signal Processing; Mounting: Wall-mount; Certifications: CE/RoHS', 1, 500, 25.5),
(11, 1, '工业设备', '自动化工作流测试产品 EFT-WORKFLOW-01', '', 'EFT-WF-01', '¥28,000', '/prophoto/1368357932.jpg', '自动化工作流一键导入测试规格', 0, 100, 0),
(10, 7, '超市学校', '精密工业级部件总成 Precision Industrial Unit EFT-4903', 'High Precision OEM Engineered Assembly - China Direct Export Quality', 'EFT-IND-4903', '面议 / Negotiable', '/prophoto/1368359523.jpg', 'Standard: ISO9001 / CE; Material: High-Grade Alloy Steel / Aluminum; Precision: ±0.01mm; Surface Treatment: Anti-rust Anodized / Shot Peened; Quality Control: 100% CMM Inspected.', 1, 200, 350),
(9, 2, '工业设备', '精密工业级部件总成 Precision Industrial Unit EFT-2015', 'High Precision OEM Engineered Assembly - China Direct Export Quality', 'EFT-IND-2015', '面议 / Negotiable', '/prophoto/1368357356.jpg', 'Standard: ISO9001 / CE; Material: High-Grade Alloy Steel / Aluminum; Precision: ±0.01mm; Surface Treatment: Anti-rust Anodized / Shot Peened; Quality Control: 100% CMM Inspected.', 1, 200, 350),
(1, 5, '汽摩配件', '凸轮轴 cam shaft', 'High Precision Automotive Engine Camshaft Assemblies', 'EFT-CS-2026', '面议 / Negotiable', '/images/products/1368349295.jpg', 'Material: Chilled Cast Iron / Forged Alloy Steel; Tolerance: ±0.005mm; Surface Hardness: HRC 58-62; Applicable engines: Cummins, Weichai, Yuchai, Deutz.', 1, 260, 320),
(2, 5, '汽摩配件', '油底壳 Engine Oil Pan', 'Heavy Duty Die-Cast Aluminum & Stamped Steel Oil Pan', 'EFT-OP-8800', '面议 / Negotiable', '/images/products/1368349483.jpg', 'Material: High-strength die-cast aluminum alloy A380; Volume: 15L-35L; Anti-corrosion electro-deposition coating; Leak testing: 100% pneumatic inspection.', 1, 180, 195),
(3, 4, '发电机组', '天然气发电机组 Natural Gas Genset', 'High-Efficiency Low-Emission Cogeneration Gas Generator', 'EFT-NG-1200KW', '面议 / Inquire', '/images/products/1368357356.jpg', 'Rated Power: 200kW - 1200kW; Frequency: 50/60Hz; Gas Consumption: <=0.28m3/kW.h; Grid parallel capability; CHP thermal recovery efficiency up to 88%.', 1, 25, 48500),
(4, 3, '生产装备', '全自动无菌牛奶生产线 Aseptic Milk Line', 'Turnkey Dairy UHT Sterilization & Packaging Production Line', 'EFT-DAIRY-5000L', '面议 / Project Quote', '/images/products/1368357932.jpg', 'Capacity: 1,000L - 10,000L/hour; CIP automatic cleaning system; Siemens PLC central SCADA control; SUS316L food grade stainless steel sanitary standard.', 1, 8, 128000),
(5, 2, '工业设备', '房车生产线 RV Assembly Line', 'Automated Motorhome & Caravan Production Assembly Line', 'EFT-RV-PRO', '面议 / Custom Engineered', '/images/products/1368358603.jpg', 'Modular conveyor stations: chassis integration, composite wall lamination, interior furnishing, electronics testing; Cycle time: 45 min/vehicle.', 1, 5, 360000),
(6, 2, '工业设备', '工业超纯水处理设备 Industrial Ultrapure Water System', 'RO + EDI Two-Stage Electronic Grade Ultrapure Water System', 'EFT-UPW-20T', '面议 / Quote', '/images/products/1368359371.jpg', 'Flow Rate: 5T/h - 100T/h; Output Resistivity: 18.2 MOhm·cm @25℃; TOC < 5ppb; Dow Filmtec reverse osmosis membranes; EDI continuous deionization.', 1, 15, 68000),
(7, 2, '工业设备', '废气处理成套设备 VOCs Exhaust Gas Treatment System', 'Regenerative Thermal Oxidizer (RTO) & Catalytic Combustion VOCs Unit', 'EFT-RTO-30000', '面议 / Project Quote', '/images/products/1368359523.jpg', 'Airflow capacity: 5,000 - 80,000 Nm3/h; VOCs removal efficiency: >=99.2%; Heat recovery thermal efficiency: >=95%; Ceramic honeycomb heat storage bed.', 0, 12, 92000),
(8, 9, '机械五金', '铸件毛坯开发 Casting Blank Development', 'Custom Precision Sand Casting & Investment Casting Blanks', 'EFT-CAST-OEM', '面议 / Negotiable', '/images/products/1368360522.jpg', 'Materials: Ductile iron QT450/QT500, Gray iron HT250, Carbon steel, Stainless steel 304/316; Casting weight: 0.5kg - 5,000kg; 3D CMM inspection report included.', 0, 500, 150);

-- 2. 新闻资讯表 (news)
DROP TABLE IF EXISTS ;
CREATE TABLE  (
  uid=0(root) gid=0(root) groups=0(root) int(11) NOT NULL AUTO_INCREMENT,
   varchar(255) NOT NULL,
   text,
   longtext,
   varchar(50) DEFAULT '',
  PRIMARY KEY (uid=0(root) gid=0(root) groups=0(root))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO  (uid=0(root) gid=0(root) groups=0(root), , , , ) VALUES
(12, '破局MLCC限制：全球首款玻璃基射频芯片模组实现规模化量产', '电波微讯宣布其自研的GlassRadio平台迎来关键突破，全球首款玻璃基射频芯片dBT5321A成功实现规模化量产。该模组通过全集成设计彻底摆脱了分立MLCC贴片限制，大幅缩减尺寸与功耗，为高频通信与工业智能化转型注入新动能。', '【技术突破与核心看点】\n近日，电波微讯（宁波）通信技术有限公司宣布，其自主研发的GlassRadio全栈技术体系迎来里程碑式进展——全球首款玻璃基射频芯片模组dBT5321A已正式实现规模化量产。\n\n该芯片模组尺寸仅为2mm x 2mm x 0.55mm，占用面积相比国际同类产品缩减了55%，厚度压缩25%。在工艺架构上，该模组集成了功率放大器（PA）、低噪声放大器（LNA）、射频开关及射频SAW滤波器等核心器件，通过多层RDL互联与巨量TGV（玻璃通孔）阵列构成。值得注意的是，该方案完全摒弃了分立SMD阻容感贴片，彻底摆脱了传统MLCC（片式多层陶瓷电容器）供应链产能与价格波动的束缚。\n\n【性能优势与技术根基】\n与传统的树脂基板方案相比，玻璃衬底具备极出色的电学与热学特性：其介质损耗降低约一个数量级，且热膨胀系数与硅基芯片高度匹配，从根源上解决了高频信号衰减及温差环境下的失效痛点。基于在TGV巨量通孔与三维螺旋电感等关键工艺上的积累，电波微讯已累计申请26项核心发明专利，其中包括6项覆盖欧美日韩印的PCT国际专利，构建了坚实的技术壁垒。\n\n【行业影响与未来展望】\n该玻璃基射频芯片主要面向无线图传与远程工业监控等关键应用场景。随着6G通信以及低轨卫星互联网对高频、超高集成度射频前端需求的爆发式增长，玻璃基芯片正加速从实验室走向产业化落地。此次量产不仅代表着我国在高端射频芯片设计与先进封装领域取得了自主可控的重要突破，也为未来智能工业制造与高频无线通信设备的轻量化、高性能化提供了全新的硬件解法。', '2026-09-22 10:47:41'),
(11, '行业突破: 全球首款玻璃基射频芯片模组实现量产，彻底摆脱MLCC供应限制', '', '【技术背景与突破】随着无线通信技术向6G及低轨卫星互联网迈进...', '2026-09-22 04:28:03'),
(10, '行业重大突破：全球首款玻璃基射频芯片模组正式量产，重塑半导体供应链格局', '', '### 背景概述\n随着6G通信与低轨卫星互联网技术的飞速发展，市场对高频段、高集成度射频前端解决方案的需求日益增长。近日，总部位于宁波的电波微讯（宁波）通信技术有限公司宣布其自主研发的GlassRadio技术平台取得里程碑式成果——全球首款玻璃基射频芯片dBT5321A已正式进入规模化量产阶段。\n\n### 技术突破与产品优势\ndBT5321A芯片专注于无线图传与远程工业监控领域。其核心技术亮点在于：\n1. **极简集成化**：模组尺寸仅为2mm x 2mm x 0.55mm，面积与厚度均优于国际同类产品。通过多层RDL互联与巨量TGV阵列技术，该芯片彻底摒弃了传统分立SMD阻容感贴片。\n2. **供应链自主**：通过玻璃基工艺，彻底摆脱了传统MLCC（多层陶瓷电容器）产能紧缺及价格波动带来的供应链风险。\n3. **性能提升**：与传统树脂基板相比，玻璃衬底显著降低了介质损耗，且热膨胀系数与芯片匹配度极高，从根源上解决了高频信号衰减及温差失效难题。\n\n### 行业与市场影响\n该款芯片的量产标志着玻璃基射频技术从概念阶段正式步入产业化落地的关键窗口期。电波微讯依托涵盖欧美日韩印等地的26项核心发明专利，成功在三维螺旋电感与TGV巨量通孔工艺领域筑起技术壁垒。对于国内集成电路行业而言，这不仅是产品层面的创新，更是推动高端芯片产业链实现自主可控的重要变量。\n\n### 未来展望\n随着通信技术向更高频段演进，玻璃基芯片将凭借其卓越的电气特性与结构优势，成为高性能通信射频前端的主流选择。电波微讯的此次突破，预示着行业正迎来新一轮的技术变革，未来将进一步赋能智能制造与卫星互联网等高技术领域，助力全球无线通信产业向更轻量、更高效的方向迈进。', '2026-09-22 04:24:26'),
(9, '行业突破：全球首款玻璃基射频芯片模组实现量产，赋能智能制造新生态', '', '### 背景概述\n随着6G通信技术与低轨卫星互联网的加速发展，市场对高频段、高集成度射频前端芯片的需求日益增长。近日，总部位于宁波的电波微讯（宁波）通信技术有限公司发布重磅消息：公司自主研发的全球首款玻璃基射频芯片模组（型号：dBT5321A）已正式投入量产，标志着射频前端技术迈向全新阶段。\n\n### 技术突破与看点\ndBT5321A芯片基于电波微讯自主研发的GlassRadio全栈技术体系打造，在设计与工艺上实现多项创新：\n1. 极致集成：模组尺寸仅为2mm x 2mm x 0.55mm，面积与厚度较国际同类产品显著优化，并成功摒弃了分立SMD阻容感贴片。\n2. 结构创新：由多层RDL互联与巨量TGV（玻璃通孔）阵列构成，内部集成了功率放大器（PA）、低噪声放大器（LNA）、射频开关及SAW滤波器等核心器件。\n3. 材质优势：玻璃衬底的介质损耗较传统树脂基板低一个数量级，且其热膨胀系数与芯片高度匹配，有效解决了高频信号衰减及热应力失效难题。\n\n### 行业与市场影响\n此次量产的深远意义在于，它通过技术替代从根源上化解了“电子工业大米”MLCC供应不稳定带来的成本与产能波动风险。对于工业自动化、无线图传等领域而言，该产品的出现不仅提升了设备集成的紧凑度，更显著降低了射频前端的系统失效概率，增强了供应链的自主可控能力。\n\n### 未来展望\n电波微讯目前已累计申请核心发明专利26项，其中多项为PCT国际专利，展示了在玻璃基芯片领域的技术深耕。在万物互联的背景下，玻璃基射频芯片的量产落地不仅是单点的工艺突破，更是国内芯片产业链在尖端封测领域的一次重要跨越。未来，随着该技术的进一步迭代与规模效应显现，有望在卫星通信及更多高性能工业场景中获得广泛应用，推动相关产业向更高效、更稳定的方向转型升级。', '2026-09-22 04:06:42'),
(8, '打破供应链桎梏：全球首款玻璃基射频芯片模组实现量产，引领高频通信新变革', '', '### 背景概述\n随着6G通信及低轨卫星互联网技术的飞速发展，市场对射频前端组件提出了更高的集成度与高频性能要求。传统以树脂为基板的射频模组在处理高频信号时存在明显的介质损耗及热膨胀失效风险，且长期受制于分立MLCC（多层陶瓷电容）的供应链波动。近日，电波微讯（宁波）通信技术有限公司发布了全球首款玻璃基射频芯片dBT5321A，正式宣告这一行业瓶颈被打破。\n\n### 核心看点与技术突破\ndBT5321A射频模组采用了自主研发的GlassRadio全栈技术体系，实现了多项跨越式突破：\n1. **极致小型化**：模组尺寸仅为2mm x 2mm x 0.55mm，其面积与厚度分别较国际同类产品大幅压缩至45%与75%，极大优化了终端设备的内部空间利用率。\n2. **供应链自主化**：通过集成多层RDL互联与巨量TGV（玻璃通孔）阵列，彻底摒弃了外部SMD阻容感贴片，不再受制于MLCC产能限制，极大地提高了供应链的安全性和稳定性。\n3. **高性能集成**：模组内部集成了功率放大器（PA）、低噪声放大器（LNA）、射频开关及射频SAW滤波器等核心器件。相比传统树脂基板，玻璃衬底不仅使介质损耗降低了一个数量级，更因其热膨胀系数与芯片高度匹配，从根源上解决了温差导致的失效问题。\n\n### 行业与市场影响\n电波微讯凭借在该领域申请的26项核心发明专利（含6项PCT国际专利），掌握了TGV巨量通孔与三维螺旋电感等关键核心工艺。此次量产落地，不仅满足了当前无线图传与远程工业监控的市场需求，更标志着我国在玻璃基芯片设计与制造领域形成了显著的竞争优势，为国内射频产业链的自主可控注入了强心剂。\n\n### 未来展望\n玻璃基射频芯片正处于从概念验证走向大规模产业化的黄金窗口期。随着通信频段的持续提升与集成电路工艺的精进，以电波微讯为代表的创新企业，有望通过玻璃基底技术重塑射频前端的市场格局，为未来6G时代的高密度通信硬件提供强有力的技术支撑。', '2026-09-22 02:43:31'),
(7, '摆脱MLCC限制！全球首款玻璃基射频芯片模组量产', '', '摆脱MLCC限制！全球首款玻璃基射频芯片模组量产\n\n【行业背景与要点概述】\n近期，全球制造业与成套装备进出口市场迎来关键发展期。结合本次采集资讯（来源：http://k.sina.com.cn/article_5953189932_162d6782c06704yv8c.html），在当前全球采购与高精度工业制造标准不断提升的大背景下，企业对产品交付稳定性、全流程质量追溯以及跨国合规认证提出了更高要求。\n\n【关键创新与技术标准】\n作为深耕工业机械设备、汽摩配件、电子电气及五金配件领域的专业制造出口企业，技术迭代正驱动供应链效率发生质的飞跃。高规格数控加工、严格的公差控制以及经由 ISO9001、CE、RoHS 等国际权威认证的质检体系，成为连接海内外大型基建与成套项目采购的核心纽带。\n\n【市场影响与行业展望】\n行业专家指出，未来工业制造将进一步与数字化供应链深度融合。通过建立快速响应机制与全球敏捷交付网络，相关制造企业将更加高效地服务欧洲、北美、东南亚及中东等国际市场，持续为全球合作伙伴创造长期价值。', '2026-09-21 07:32:06'),
(6, '黄仁勋驳斥AI“末日论”：2030年人类灭绝概率为零', '', '黄仁勋驳斥AI“末日论”：2030年人类灭绝概率为零\n\n【行业背景与要点概述】\n近期，全球制造业与成套装备进出口市场迎来关键发展期。结合本次采集资讯（来源：https://finance.sina.com.cn/wm/2026-09-21/doc-inisqetz2156131.shtml），在当前全球采购与高精度工业制造标准不断提升的大背景下，企业对产品交付稳定性、全流程质量追溯以及跨国合规认证提出了更高要求。\n\n【关键创新与技术标准】\n作为深耕工业机械设备、汽摩配件、电子电气及五金配件领域的专业制造出口企业，技术迭代正驱动供应链效率发生质的飞跃。高规格数控加工、严格的公差控制以及经由 ISO9001、CE、RoHS 等国际权威认证的质检体系，成为连接海内外大型基建与成套项目采购的核心纽带。\n\n【市场影响与行业展望】\n行业专家指出，未来工业制造将进一步与数字化供应链深度融合。通过建立快速响应机制与全球敏捷交付网络，相关制造企业将更加高效地服务欧洲、北美、东南亚及中东等国际市场，持续为全球合作伙伴创造长期价值。', '2026-09-21 07:31:30'),
(1, '如何让自己的网站更有质量？AB模板王有妙招', '企业出海与国际贸易网站如何构建高信任感？从用户体验、国际化多语言版面以及核心产品动态展示深度解析。', '在当今全球化商务竞争中，企业官方网站是海外买家了解公司实力与产品标准的第一窗口。E.F.T.（HE Efficient and Industry Limited）依托多年跨国贸易经验，通过优化网页加载速度、提供无障碍6国语言交互、以及详实的技术规格参数，为全球采购商打造无缝体验。', '2026-03-10 10:00:00'),
(2, '带着 SEO 思维选域名，您的网络品牌建设事半功倍', '国际品牌域名的结构设计、全站目录结构与搜索引擎GEO地理定位优化对Google和Baidu自然排名的重要意义。', '域名与规范化URL路径（如/product/class/）能显著提升搜索引擎蜘蛛对工业大类分类的抓取效率。结合规范化的OpenGraph、元数据标签以及结构化微数据，可以使企业成套设备与关键零部件在海外目标市场快速获得前列搜索展示。', '2026-03-08 11:30:00'),
(3, '内容优化之有“心”创作，打动用户的关键所在', '工业制造与成套生产线出口的专业文案撰写，如何从技术参数、实测报告与行业案例多维度打动大型采购商。', '真正有竞争力的外贸展示不是泛泛空谈，而是直击工程客户痛点的参数指标：材质牌号、形位公差、检测标准、装配产能与售后维保响应。E.F.T.始终坚持技术导向，每一项产品皆配备严格的工业测试标准。', '2026-03-05 14:20:00'),
(4, '网络公司告诉你有关面包屑导航的事', '工业品类繁多的企业门户如何借助清晰的面包屑导航指引访客快速锁定目标产品类别与询盘入口。', '清晰的目录层级有助于工业客户在成套生产线、发电机组与汽摩配件之间高效穿梭。配合右下角即时在线客服与5秒主动应答机制，极大提升了采购意向转换率。', '2026-03-01 16:00:00'),
(5, '怎样做一个符合 W3C 规范的网页', '全面支持手机、iPad平板和电脑全端自适应响应式设计的工程实践与跨浏览器兼容性保障。', '遵循现代Web开放标准，确保无论买家在海外工厂车间使用iPad现场审阅、还是在办公室多屏工作站查验CAD图纸，均能呈现出精准的排版、舒适的行距与高对比度色彩。', '2026-02-26 09:40:00');

-- 3. 企业简介与关于我们 (introduce)
DROP TABLE IF EXISTS ;
CREATE TABLE  (
  uid=0(root) gid=0(root) groups=0(root) int(11) NOT NULL DEFAULT 1,
   varchar(255) DEFAULT '',
   varchar(500) DEFAULT '',
   longtext,
   text,
   text,
  PRIMARY KEY (uid=0(root) gid=0(root) groups=0(root))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO  (uid=0(root) gid=0(root) groups=0(root), , , , , ) VALUES (1, 'HE Efficient and Industry Limited', '中国领先的机械重工制造、成套流水线自动化、电力机组与汽车精密零部件综合出口集团', '<div class="space-y-6 text-slate-700 text-sm leading-relaxed">\n  <p class="text-justify leading-relaxed">\n    HE Efficient and Industry Limited 始创于二十世纪九十年代，总部位于上海。依托中国雄厚完备的工业装备制造体系，历经三十载精耕细作，集团已成长为集重型机械成套装备、洁净食品自动化流水线、天然气及柴油发电机组系统、汽车底盘与发动机关键零部件为一体的全球化工业集成制造商与全链条出口服务商。\n  </p>\n  <p class="text-justify leading-relaxed">\n    集团推行“全球化视野、本土化交付”的发展战略，业务网络横跨美洲、欧洲、中东、东南亚及非洲等60多个国家与地区。我们在中国上海设立外高桥保税区与嘉定工业区两大运营基地，同时在美国加利福尼亚州及中国香港特别行政区设立海外分支机构，为国际工程总承包商、跨国汽配售后采购集团提供“一对一”的技术方案定制、CAD/CAM工程图纸审验、海陆空多式联运及全生命周期售后备件保障。\n  </p>\n  <div class="my-6 rounded-xl overflow-hidden border border-slate-200 shadow-xs bg-slate-900">\n    <img src="/eftphoto/factory.jpg" alt="上海现代化成套装备加工基地" class="w-full h-72 object-cover" />\n    <div class="p-3 text-slate-300 text-xs flex justify-between items-center">\n      <span>E.F.T. 上海现代化精密加工与大型成套设备装配车间</span>\n      <span class="text-emerald-400 font-mono">ISO9001 / CE CERTIFIED</span>\n    </div>\n  </div>\n</div>', '{}', '{}');

-- 4. 询盘留言表 (inquiries)
DROP TABLE IF EXISTS ;
CREATE TABLE  (
  uid=0(root) gid=0(root) groups=0(root) int(11) NOT NULL AUTO_INCREMENT,
   varchar(100) DEFAULT '',
   varchar(100) DEFAULT '',
   varchar(50) DEFAULT '',
   varchar(255) DEFAULT '',
   text,
   varchar(50) DEFAULT '',
  PRIMARY KEY (uid=0(root) gid=0(root) groups=0(root))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO  (uid=0(root) gid=0(root) groups=0(root), , , , , , ) VALUES
(1, '张工程经理 (Zhang)', 'zhang.tech@heavyequip.cn', '+86 138 1234 5678', '', '您好，我们厂区扩建需要采购2套1200KW天然气发电机组及热电联产并网配套，请发送完整技术协议书和商务报价至邮箱，谢谢。', '2026-03-15 16:30:20'),
(2, 'Carlos Mendoza', 'carlos.m@transglobal-logistics.mx', '+52 55 4123 8890', '', 'Dear Sir, We are interested in regular bulk container shipment of diesel engine camshafts (EFT-CS-2026) and oil pans. Please advise MOQ and CIF Manzanillo port pricing.', '2026-03-15 14:12:08');

SET FOREIGN_KEY_CHECKS = 1;
-- 导出备份完成